image: node:20

stages:
  - build

before_script:
  - apt-get update && apt-get install -y python3-pip
  - pip3 install -r requirements.txt
  - npm install -D tailwindcss
  - npx tailwindcss -i ./input.css -o ./assets/styles.css --minify

pages:
  stage: build
  script:
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - main
