site_name: JavaScript Course

theme:
  name: material
  language: fi
  palette:
    scheme: default
    primary: blue
    accent: indigo

nav:
  - Etusivu: index.md
  - Moduulit:
      - "Moduuli 1 – Perusteet": moduuli1.md
      - "Moduuli 2 – Funktiot ja rakenteet": moduuli2.md
      - "Moduuli 3 – Olio-ohjelmointi ja tapahtumat": moduuli3.md
      - "Moduuli 4 – Asynkroninen ohjelmointi": moduuli4.md
